 - name: task level variables
   hosts: local
   connection: local
   tasks:
    - name: Print Course Info
      ansible.builtin.debug:
        msg: "CourseName is {{ COURSE }} ,Duration is {{ DURATION }}, Trainer is {{ TRAINER }} "

