 - name: filelevel variables
   hosts: local
   connection: local
   vars_files: 
     - course.yaml
   tasks:
    - name: Print Course Info
      ansible.builtin.debug:
        msg: "CourseName is {{ COURSE }} and Duration is {{ DURATION }}"